" turn hybrid line numbers on
:set number relativenumber
:set nu rnu

" defaut tab
:set shiftwidth=2
:set softtabstop=2
:set tabstop=2

" set Rust tab
autocmd Filetype rust setlocal ts=4 sw=4 sts=4 expandtab

" ### vim-plug ###
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'cespare/vim-toml'
Plug 'rust-lang/rust.vim'

" Initialize plugin system
call plug#end()
